// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO2RF75GZSu2seT3HXayQErd79ek1r16A',
    appId: '1:220181038206:web:f5586bf78ee227ee4a042f',
    messagingSenderId: '220181038206',
    projectId: 'girgo-prod',
    authDomain: 'girgo-prod.firebaseapp.com',
    storageBucket: 'girgo-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg00uGiR3KeQVXVX9znpZHw9FS1kX401U',
    appId: '1:220181038206:android:106be048fc2833064a042f',
    messagingSenderId: '220181038206',
    projectId: 'girgo-prod',
    storageBucket: 'girgo-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXBCotNuuwjmYEbx1sFj1SmIaAAjliDbQ',
    appId: '1:220181038206:ios:6777de8331f438bc4a042f',
    messagingSenderId: '220181038206',
    projectId: 'girgo-prod',
    storageBucket: 'girgo-prod.firebasestorage.app',
    iosBundleId: 'com.anamaya.girgo',
  );
}
